# Generated by Django 4.2.7 on 2024-04-26 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoqueADS', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='categoria',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='estoqueADS.categoria'),
            preserve_default=False,
        ),
    ]
