# Generated by Django 4.2.7 on 2024-05-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoqueADS', '0004_produtos_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
